services:
  potty-tracker:
    image: ruby:3
    volumes:
      - ruby_bundle:/usr/local/bundle
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "bundle install && bundle exec ruby main.rb"

volumes:
  ruby_bundle:
