services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGUSER: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mqtt-client:
    image: ruby:3
    volumes:
      - ruby_bundle:/usr/local/bundle
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "bundle install && bundle exec ruby mqtt-client.rb"

volumes:
  ruby_bundle:
  postgres_data:
